# -*- coding: utf-8 -*-
"""pandas-09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UunYvzfCXknZ4SmsobeP9nspJVUrPbvw
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

x = np.array([1,5,9])
countries = ["USA", "Rosja", "Kanada"]
m_bronze = np.array([12, 10, 8])
m_silver = np.array([4,2,8])
m_gold = np.array([2,2,1])

plt.figure(figsize=(11,7))
plt.bar(x, m_bronze, color="brown", width=0.5, label="B")
plt.bar(x+0.5, m_silver, color="silver", width=0.5, label="S")
plt.bar(x+1, m_gold, color="gold", width=0.5, label="Z")
plt.xticks(x+0.5, countries)

plt.legend(ncol=3, loc="best");

# plt.savefig("plik1.jpg", dpi=150)
# plt.savefig("plik1.pdf")

# wykres kołowy

names=["Jaś", "Ania", "Gosia", "Marek"]
toys=[10,7,17,6]
colors=["red", "yellowgreen", "#FF0066", "#FFFF00"]

plt.figure(figsize=(8,6))
plt.pie(toys, labels=names, autopct="%.1f %%", shadow=True, colors=colors, explode=[1,1,3,2]);

import seaborn as sns

df = pd.read_csv("http://51.91.120.89/extras/gapminderDataFiveYear.csv").query("year==2007")
df

colors=["yellow", "red", "gray", "green", "blue"]
sns.lmplot(data=df, x="lifeExp", y="gdpPercap", fit_reg=False, aspect=2.5, hue="continent", palette=colors)
plt.grid()

sns.lmplot(data=df, x="lifeExp", y="gdpPercap", fit_reg=False, aspect=0.8, hue="continent", palette=colors, col="continent")

sns.jointplot(df["lifeExp"], df["gdpPercap"], kind="scatter")

sns.jointplot(df["lifeExp"], df["gdpPercap"], kind="hex")

sns.jointplot(df["lifeExp"], df["gdpPercap"], kind="kde")

!wget -O covid.csv https://cutt.ly/alx-covid

df = pd.read_csv("covid.csv")
df.head()

df["Date_reported"] = pd.to_datetime(df["Date_reported"], format="%Y-%m-%d")

plt.figure(figsize=(15,8))
sns.lineplot(data=df.query(" Country_code=='PL' and Date_reported>='2021-09-01' "), x="Date_reported", y="New_cases", color="red", marker="o")
sns.lineplot(data=df.query(" Country_code=='PL' and Date_reported>='2021-09-01' "), x="Date_reported", y="New_cases", color="blue", marker="o")
plt.grid();

plt.figure(figsize=(15,8))
sns.lineplot(data=df.query(" Country_code in ['PL', 'DE', 'GB'] and Date_reported>='2021-09-01' "),
             x="Date_reported", y="New_cases", color="red", marker="o", hue="Country_code")
plt.grid();

#wykres słupkowy
sns.get_dataset_names()

df = sns.load_dataset("titanic")
df

df["class"].value_counts()

sns.countplot(data=df, y="class")

sns.countplot(data=df, x="class", hue="sex")

df = sns.load_dataset("car_crashes").sort_values("total", ascending=False)
df

plt.figure(figsize=(10,15))
sns.barplot(data=df, x="total", y="abbrev", color="b", label="total")
sns.barplot(data=df, x="alcohol", y="abbrev", color="r", label="alko")
plt.legend();

#wykres pudełkowy
df= pd.read_csv("http://51.91.120.89/extras/pokemon.csv")
df

plt.figure(figsize=(12,14))
sns.boxplot(data=df, x="Attack", y="Type 1", color="r")

plt.figure(figsize=(22,9))
sns.boxplot(data=df, y="Attack", x="Type 1", color="b", hue="Legendary")

#wykres heatmap
df = sns.load_dataset("flights")
df

df1 = pd.pivot_table(df, index="month",  )

plt.figure(figsize=(7,7))
sns.heatmap(df1, annot=True, fmt="d", cmap="jet")

plt.figure(figsize=(7,7))
sns.heatmap(df1, annot=True, fmt="d", cmap="jet_r")